name: Deploy server app to ECR

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    name: Deploy server app to ECR
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: server
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup AWS
        uses: ./.github/actions/setup-aws

      - name: Login to ECR
        run: aws ecr get-login-password --region eu-central-1 | docker login --username AWS --password-stdin 185226996869.dkr.ecr.eu-central-1.amazonaws.com

      - name: Build image
        run: docker build -t api-repo-dev .

      - name: Tag image
        run: docker tag api-repo-dev:latest 185226996869.dkr.ecr.eu-central-1.amazonaws.com/api-repo-dev:latest

      - name: Push image
        run: docker push 185226996869.dkr.ecr.eu-central-1.amazonaws.com/api-repo-dev:latest
